# Generated by Django 4.2.13 on 2024-06-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_status', models.CharField(choices=[('NOT STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='NOT STARTED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'todolist',
            },
        ),
    ]
